export const eventsData = [
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "held",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "pending",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "pending",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "canceled",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "pending",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "conducted",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
  {
    id: 1,
    title: "Вокршоп для новичков",
    course: {
      id: 1,
      image: "",
      title: "Акции и торговля",
    },
    status: "canceled",
    event_date: "2023-09-04",
    visitors_max: 1500,
    visitors: 500,
  },
];

export const eventData = {
  id: 1,
  title: "Вокршоп для новичков",
  description: "Как делать технический анализ криптовалюту",
  event_date: "2023-09-04",
  status: "pending",
  visitors_max: 1500,
  visitors: 0,
};

export const eventsDataSingle = [
  {
    id: 1,
    user: {
      id: 1,
      full_name: "Александр",
      image: "",
    },
    flow: {
      id: 1,
      title: "Pro",
      type: "Общий",
    },
    is_visited: false,
    course_time: 7827,
    current_time: 7328,
    attempts: 12,
    point: 10,
    max_point: 100,
    visited_date: "2023-12-12 12:12:12",
  },
  {
    id: 1,
    user: {
      id: 1,
      full_name: "Александр",
      image: "",
    },
    flow: {
      id: 1,
      title: "Pro",
      type: "Общий",
    },
    is_visited: true,
    course_time: 7827,
    current_time: 7328,
    attempts: 12,
    point: 10,
    max_point: 100,
    visited_date: "2023-12-12 12:12:12",
  },
];
